### ISSUE TITLE
Snippet to show a hide password HTML CSS JS

### ISSUE THREAD

**Issue by Sowham-3098** [avincodes/Web-dev-Snippets#28]
Can I add this snippet?

**Comment by avincodes** [comment]
Go for it! @Sowham-3098

**Comment by Sowham-3098** [comment]
Then please assign me this task and add Hactoberfest tag

**Comment by Sowham-3098** [comment]
@avincodes Please assign this task to me and add the Hacktoberfest Tag

**Comment by avincodes** [comment]
Hi @Sowham-3098 the hacktoberfest PR counts from the tag on the pull request, not the tag on the issue, so don't worry about it! You can work on it...

**Comment by neeraj542** [comment]
can i work on this issue
