### ISSUE TITLE
CSS animation buttons

### ISSUE THREAD

**Issue by Bhavya-C-ai** [avincodes/Web-dev-Snippets#38]
I would like to contribute at least 20 different buttons animations and styling :)
can you assign this to me under hacktober label, thanks!

**Comment by yosaami** [comment]
I would like to contribute to this, I'm new to open source and looking for a beginner friendly contribution. Please assign me. thanks.

**Comment by rohit-raj-01** [comment]
@avincodes
 please assign it to me.

**Comment by avincodes** [comment]
@Bhavya-C-ai go ahead!

**Comment by ayushi-ras** [comment]
please assign me
