### ISSUE TITLE
Add live weather reports web page

### ISSUE THREAD

**Issue by AbhishekKumar2002** [avincodes/Web-dev-Snippets#45]
Hi @avincodes  Please assign me this issue with Hacktoberfest Label. I will use simple HTML, CSS and JAVASCRIPT. It will gives you the weather information about the place you search.

**Comment by avincodes** [comment]
Sure go for it!

**Comment by AbhishekKumar2002** [comment]
I have added Live weather Web Page. Please Check it and accept my PR.
