### ISSUE TITLE
I would like to add a snippet of scroll to top button. 

### ISSUE THREAD

**Issue by DEV-Dhruva** [avincodes/Web-dev-Snippets#52]
Hey @avincodes , will you assign this issue to me

**Comment by avincodes** [comment]
Go for it @DEV-Dhruva!

**Comment by avincodes** [comment]
@DEV-Dhruva any update?

**Comment by DEV-Dhruva** [comment]
Hey @avincodes , I have complete the issued task and you already merged my pr 2 days ago.
