### ISSUE TITLE
Create a contributors Guide!

### ISSUE THREAD

**Issue by avincodes** [avincodes/Web-dev-Snippets#56]
- [ ] Please created a contributors guide which includes the need to add a readme file with a screenshot of the snippet running as well!

**Comment by avincodes** [comment]
@ItsMyBlackAxe you can take up this issue!

**Comment by sushantgwr87** [comment]
If this is open to work then I would like to work on this under Hacktoberfest.

**Comment by iqrafirdose** [comment]
Hey! I want to work on this issue . Can you assign me?

**Comment by avincodes** [comment]
Sorry @yindrasoma is already working on it!
