### ISSUE TITLE
Add Calculator

### ISSUE THREAD

**Issue by AbhishekKumar2002** [avincodes/Web-dev-Snippets#70]
Hi @avincodes, I would like to add a Calculator using HTML, CSS and JAVASCRIPT. I request you to assign it to me under Hacktoberfest label.

**Comment by avincodes** [comment]
@AbhishekKumar2002 You can go for it! I will assign the issue! And also the label in the pull request is what counts, not the issue! A lot of people do not know that!

**Comment by ankit060801** [comment]
hello sir please assign this task to me

**Comment by chaotic-10** [comment]
Hello @avincodes, I would like to contribute to this task, so if you could assign it to me under the Hacktoberfest label.

**Comment by AbhishekKumar2002** [comment]
Hi @avincodes I have added the calculator web page. Please accept my PR
